---
title: "Page Visits Funnel"
output: html_notebook
---

```{r message = FALSE, error=TRUE}
# load packages
library(readr)
library(dplyr)
```

```{r message = FALSE, error=TRUE}
# load data
visits <- read_csv("visits.csv")
cart <- read_csv("cart.csv")
checkout <- read_csv("checkout.csv")
purchase <- read_csv("purchase.csv")
```

```{r error=TRUE}
# inspect data frames
head(visits)
head(cart)
head(checkout)
head(purchase)
```

```{r error=TRUE}
# define visits_cart here:
visits_cart <- visits %>%
left_join(cart,
by = c('user_id'='user_id'))
visits_cart


```

```{r error=TRUE}
# define total_visits here:
nvisits <- nrow(visits)
nvisits
```

```{r error=TRUE}
# define visit_no_cart here:
visits_nocart <- visits_cart %>%
filter(is.na(cart_time))
nvisits_nocart <- nrow(visits_nocart)
nvisits_nocart

```

```{r error=TRUE}
# calculate visit_no_cart_percent here:
no_cart_percent <- nvisits_nocart/nvisits
no_cart_percent
```

```{r error=TRUE}
# define cart_checkout here:
cart_checkout <- cart %>%
left_join(checkout, 
by = c('user_id'='user_id'))
cart_checkout


```

```{r error=TRUE}
# define total_carts here:
ncarts <- nrow(cart)
ncarts
```

```{r error=TRUE}
# define cart_no_checkout here:
cart_no_checkout <- cart_checkout %>%
filter(is.na(checkout_time))
ncart_no_checkout <- nrow(cart_no_checkout)
ncart_no_checkout


```

```{r error=TRUE}
# calculate cart_no_checkout_percent here:
cart_no_checkout_percent <- ncart_no_checkout / ncarts
cart_no_checkout_percent
```

```{r error=TRUE}
# define all_data here:
all_data <- visits %>%
left_join(cart) %>%
left_join(checkout) %>%
left_join(purchase)

head(all_data)



```

```{r error=TRUE}
# define total_checkout here:
ncheckout <- nrow(checkout)
ncheckout

```

```{r error=TRUE}
# define checkout_no_purchase here:
checkout_purchase <- checkout %>%
left_join(purchase)
checkout_no_purchase <- checkout_purchase %>%
filter(is.na(purchase_time))
ncheckout_no_purchase <- nrow(checkout_no_purchase)
ncheckout_no_purchase

```

```{r error=TRUE}
# calculate checkout_no_purchase_percent here:
checkout_no_purchase_percent <- ncheckout_no_purchase/ncheckout
checkout_no_purchase_percent

#which step of the funnel is weakest (ie. has the highest percentage of users not completing it? )
no_cart_percent
cart_no_checkout_percent
checkout_no_purchase_percent
#no_cart_percent is weakest
```

```{r error=TRUE}
# update all_data with time_to_purchase column here:
all_data <- all_data %>%
mutate(time_to_purchase = purchase_time - visit_time)

```

```{r error=TRUE}
# inspect the updated all_data data frame here:
head(all_data)
```

```{r error=TRUE}
# define time_to_purchase here:
time_to_purchase <- all_data %>%
summarize(mean_time = mean(time_to_purchase, na.rm = TRUE))
time_to_purchase


```